# Generated by Django 3.0.7 on 2020-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('url', models.CharField(max_length=200, verbose_name='项目URL')),
                ('status', models.ImageField(default=0, upload_to='', verbose_name='测试状态')),
            ],
        ),
    ]
